### ISSUE TITLE
"Direct installation" of Lucene indexes into Solrini

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#1010]
Solr is basically just a webapp around Lucene. It is possible to bypass the Solr indexing REST APIs and just directly copy the Lucene indexes into the right path in the Solr directory structure. We should provide documentation on how to do this, to save users an extra indexing step.

**Comment by edwinzhng** [comment]
Looked into it a bit, according to the steps [here](https://stackoverflow.com/a/35927597) from 2016, we should:

1. Explicitly create the Solr schema via the JSON API for **all** fields (will need to add more on top of the existing schema scripts). This is also good since we can control types in one place instead of letting Solr infer the field type like it does right now. Probably makes sense to do #1009 first

2. Change the "dataDir" in solrconfig.xml to point to the Lucene index

**Comment by lintool** [comment]
hey @r-clancy you did this before, right? can you comment on whether @edwinzhng 's on the right track?

@edwinzhng for step 2 above we have pre-built indexes here: https://git.uwaterloo.ca/jimmylin/anserini-indexes

We can get just `wget` it and uncompress into the location that Lucene expects it... so we won't even need to change the `dataDir`?

**Comment by r-clancy** [comment]
@lintool Yeah, I had done this before. @edwinzhng is on the right track - the process is just making sure the Solr schema aligns with the Lucene schema and copying the Lucene index (or changing the Solr data dir to point to the Lucene index) into the correct place.
