### ISSUE TITLE
covidsearch.io improvements

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#1060]
A few things I noticed playing with the interface.

1. We should probably mark bioarxiv and medarxiv papers prominently, since they're not peer reviewed. Also, they don't appear in a facet under "Journal". They should?

2. Also, we seemed to have discovered the secrets to communicating from the future...

<img width="844" alt="Screen Shot 2020-03-23 at 10 33 11 PM" src="https://user-images.githubusercontent.com/313837/77382255-4b876180-6d56-11ea-88c2-cd2aaa2e2f47.png">

Or, more mundanely, we need better date parsing. I noticed that dates appear in many inconsistent formats. Should dates be standardized upstream from the AI2 end?

**Comment by edwinzhng** [comment]
1 - they're faceted under "source" since that's where the dataset indicates biorxiv and medarxiv, I can add the indicator though

2 - dates are just weird from upstream, hopefully they can just update it for the next dataset release but in the meantime we could just display year only to keep it simple?

**Comment by lintool** [comment]
Confirmed with AI2 that (2) is an upstream data issue. (1) has been fixed.
