### ISSUE TITLE
Colab demo that demonstrates integration with SciBERT - Error

### ISSUE THREAD

**Issue by dinasayed** [castorini/anserini#1089]
First, thank you very much for sharing these demos for working with Covid-19 dataset:
 https://github.com/castorini/anserini/blob/master/docs/experiments-covid.md

Well, I am trying to run : Colab demo that demonstrates integration with SciBERT
But when I changed the query to 'what are the effectiveness of drugs being developed and tried to treat COVID-19 patients'
the notebook fails to complete running when extract contextualized vectors of all the paragraphs from the hit #7

Below is the error:
---------------------------------------------------------------------------

KeyError                                  Traceback (most recent call last)

<ipython-input-47-f986da5a4d88> in <module>()
      3 
      4 paragraph_states = []
----> 5 for par in tqdm(doc_json['body_text']):
      6     state = extract_scibert(par['text'], tokenizer, model)
      7     paragraph_states.append(state)

KeyError: 'body_text'

**Comment by tteofili** [comment]
the issue here is that not all documents have `body_text` (the full text of the article content) available (you can also see that there is a check for that in `show_document` method too).
The doc no. 7 in search results on your query doesn't have full text and hence the error.

For the sake of demo / trying out the notebook, I'd suggest selecting a different document that has full text, otherwise you have to use some other text to feed to SciBERT, like the abstract.
You can do that with something like this:

`paragraph_states = []
if 'body_text' in doc_json: 
  for par in tqdm(doc_json['body_text']):
      state = extract_scibert(par['text'], tokenizer, model)
      paragraph_states.append(state)
else:
  paragraph_states.append(extract_scibert(doc_json['abstract'], tokenizer, model))`

However please note that you may also have to tweak following cells that assume 'body_text' is available.
Final note: there's also a newer version of the same index (from April 4th) we can use in that notebook (as you can see from the experiments-covid doc page).

**Comment by lintool** [comment]
Having heard no follow up, closing. Reopen if necessary.
