### ISSUE TITLE
Better tokenization for COVID-19 and related terms

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#1091]
Anserini currently uses [`DefaultEnglishAnalyzer`](https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/analysis/DefaultEnglishAnalyzer.java), but tokenizes "COVID-19" into "COVID" and "19". It'd be nice to fix this.

Other related terms - 2019-nCoV and SARS-CoV-2.

Perhaps the solution is to implement a `DefaultCovidEnglishAnalyzer` that subclasses `DefaultEnglishAnalyzer`? Takes a static list of tokens that's explicitly is _not_ broken up?

**Comment by tteofili** [comment]
I've added a first version of such an Analyzer which uses Lucene's ClassicAnalyzer instead of StandardAnalyzer.
Another possible improvement would be not to lowercase tokens related to e.g. proteins, like "A protein" becomes "a" and "protein" and so a very relevant term would finish in the bucket of highly unrelevant (or even stopwords) terms.
