### ISSUE TITLE
Problem when using WaPov3 with TREC2019 backgroundlinking topic

### ISSUE THREAD

**Issue by ChanikanWitt** [castorini/anserini#1327]
Hi,
I try using WaPo v3 with last year topic - Trec2019 backgroundlinking to produce a baseline. However, I faces this problem "java.lang.IllegalArgumentException: docID must be >= 0 and < maxDoc=671945 (got docID=-1)".
![image](https://user-images.githubusercontent.com/61763654/88176185-167e1380-cc51-11ea-8085-cb88258d8c9e.png)
The result file from this error in .txt file is incomplete like this.
![image](https://user-images.githubusercontent.com/61763654/88176702-dcf9d800-cc51-11ea-8cab-3e569d488cc4.png)

**Comment by PepijnBoers** [comment]
Hi @ChanikanWitt I came across this issue as well. The problem here is that some topic articles cannot be found in the index you're using. This is caused by the removal of near-duplicates in the third version of the WaPo collection. For the 2019 topics this means that there is another version of the missing topic article present in the collection (having a different docid). If you want to use the topics from last year I would advice you to use WaPo v2.
