### ISSUE TITLE
Collection vs Generator

### ISSUE THREAD

**Issue by MarcosFP97** [castorini/anserini#1579]
Hi, 

First of all, congrats for the outstanding work with Anserini project. I am a bit confused about the difference between some indexing parameters. In concrete, *collection* and *generator*. 

To my understanding, I need to set collection to the dataset that I am using, in my case `C4Collection`, but I don't know if it needs a specific generator or it can be anyone, e.g., `DefaultLuceneDocumentGenerator` or `WarcGenerator`.

I would appreaciate any help, and thank you again.

Best,
Marcos

**Comment by lintool** [comment]
+ A `Collection` is responsible for reading the text from disk in a particular format (JSON, WARC, TREC, etc.).
+ A `Generator` is responsible for generating a Lucene document, e.g., populating the right fields to index.

Over time, we've tried to make `DefaultLuceneDocumentGenerator` "do the right thing", so in most case, if you use it, it'll be okay. Every time we get a new corpus in a different format, though, we need to build a new `Collection`.

Specifically, in our case, to index C4, I use:

```
nohup sh ./target/appassembler/bin/IndexCollection -collection C4Collection \
 -generator C4Generator -threads 96 -input /store/collections/c4/en.clean-train-json \
 -index indexes/c4-all.compact -storeRaw >& logs/log.c4.compact &
```

It is because we're indexing "custom" fields for C4.

Make sense?

**Comment by MarcosFP97** [comment]
Dear @lintool, 

Thank you very much for your clear explanation. It makes perfect sense. However, I was wondering if `DefaultLuceneDocumentGenerator` will also populate the right fields to index for the C4 collection.

Best,
Marcos

**Comment by lintool** [comment]
Mostly, since C4 generator subclasses default Lucene generator:
https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/index/generator/C4Generator.java#L53

You won't be able to fetch based on URLs and time, I think.

**Comment by MarcosFP97** [comment]
Perfect, thanks for your assistance :) I am closing the issue
