### ISSUE TITLE
Add synonyms for search

### ISSUE THREAD

**Issue by mpandeydev** [castorini/anserini#1610]
Have the capability to specify synonyms for search, e.g., lift vs elevator, slow vs gradual. If this feature is already present, will appreciate the specific instructions, and this issue should then be closed.

**Comment by lintool** [comment]
Lucene already provides synonym queries, e.g., `SynonymQuery` or `DisjunctionMaxQuery`, depending on what you want.

Since Anserini is just a wrapper around Lucene, you can compose whatever query you want and pass to Anserini to evaluate, e.g., with https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/search/SimpleSearcher.java#L561

If you want to do this in Python, see here: https://github.com/castorini/pyserini/blob/master/docs/usage-querybuilder.md
