### ISSUE TITLE
Address end-to-end effectiveness instability issues

### ISSUE THREAD

**Issue by lintool** [castorini/Anserini#252]
In running end-to-end regression experiments, we observe a small amount of effectiveness instability (MAP and P3) - differences are small, mostly in the fourth decimal place.

This is due to tie-breaking behavior of documents with the same score, which is dependent on the order the documents were added to the index (which is non-deterministic due to multi-threaded indexing).

We should address this issue.

**Comment by Peilin-Yang** [comment]
> This is due to tie-breaking behavior of documents with the same score, which is dependent on the order the documents were added to the index (which is non-deterministic due to multi-threaded indexing).

`trec_eval` ranks the documents by scores and breaks the ties using the external document ids string in descending order. See the test: https://github.com/castorini/Anserini/blob/master/src/test/java/io/anserini/eval/RankingResultsTest.java#L30

So the tie-breaking behavior of `trec_eval` is deterministic. 
In order to support the feature such as treating the docId as Integer or breaking the tie by docId in ascending order, I have added these features and tests. See: https://github.com/castorini/Anserini/blob/master/src/main/java/io/anserini/eval/EvalArgs.java#L33-L42

**Comment by lintool** [comment]
Issue fixed for newswire, gov2, and wt10g collections, complete with update regression experiments - commit 014ebac27539f80f0d3fe980c780f6c3aa0fa367

Merged as part of #253
