### ISSUE TITLE
SourceDocument refactoring to get rid of readNextRecord

### ISSUE THREAD

**Issue by lintool** [castorini/Anserini#254]
I don't remember who originally designed the interface, and it could have very well been me - but it doesn't make sense to me that `readNextRecord` is a method in `SourceDocument`.

`SourceDocument` is an object within a container class (`FileSegment`). It shouldn't need to know about "what's next" - that should be the responsibility of the container?

**Comment by borislin** [comment]
I'll start working on this after #332 is merged

**Comment by lintool** [comment]
@borislin sg

As part of this issue, we should clean up the semantics of `FileSegment`. It's supposed to be an iterator over documents, right? Except we haven't implemented "true" iterators - `hasNext()` doesn't actually do much... we basically keep on calling `next()` until we run out of file... and use `null` to signal no more record. This is janky.

In a "true" iterator impl, `hasNext()` should be advancing the record, and `next()` actually returns it...

Let's make it actually work correctly. And properly tested.

**Comment by borislin** [comment]
@lintool

So we should have a buffer variable `bufferRecord` to store the record obtained in `hasNext()`.

In `hasNext()`, if `bufferRecord` is null and there are more records in the file, we should store the next record into `bufferRecord`. Otherwise, don't advance the record and just return (to tackle the case when user calls `hasNext()` multiple times without calling any `next()`). Also, return `false` when `bufferRecord` is null and the file has reached `EOF`.

In `next()`, we first check if `bufferRecord` is null. If yes, call `hasNext()` first. If no, return `bufferRecord` and set `bufferRecord` to null.

Good?

**Comment by lintool** [comment]
sg, and throw `NoSuchElementException` when you run off the end...

**Comment by borislin** [comment]
Refactored in #352
