### ISSUE TITLE
Implement Condensed List Relevance Models

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#422]
Implement -

Diaz, Condensed List Relevance Models. ICTIR 2015
https://dl.acm.org/citation.cfm?id=2808194.2809491

Should be fairly straightforward.

**Comment by lintool** [comment]
@aalbahem perhaps this would be an easy issue for you to tackle? A very simple (although not particularly efficient implementation) would be to add a filter clause on the RM3 query, restricting to only the docids in the original retrieved set.

**Comment by aalbahem** [comment]
@lintool I will start with this first.

**Comment by aalbahem** [comment]
@lintool I wonder what will be the right implementation strategy:

- Should we create a different class (somehow duplicate RM3)?

- Modify the SearchCollection class to include a parameter for the condense list reranker and pass the initial query as a filter. Nevertheless, this also means we need to modify the RerankerContext so that the filter parameter is a list of queries not a single query. Will this refactoring cause many changes in different places?

**Comment by lintool** [comment]
I'm thinking of a slightly different approach along the lines of your first proposal, although we probably want to refactor the original RM3 reranker implementation to reduce code duplication as much as possible...

**Comment by aalbahem** [comment]
@lintool I have refactored Rm3Reranker to reduce redundancy, and I also created  Condensed List Relevance cass . Nevertheless, I implemented the re-scoring using Lucene QueryRescorer API. Unfortunately, that can not not work with Lucene sorting. So, for the time being, I am not implementing the sorting function as it was the case with Rm3reranker. Let me know what you think.

**Comment by lintool** [comment]
Hi @aalbahem thanks for your contributions!

1. Do you have effectiveness results?
2. Can you send a PR for me to look at?

**Comment by lintool** [comment]
Doesn't seem to be any interest in this (anymore)...
