### ISSUE TITLE
Implement term dependence model

### ISSUE THREAD

**Issue by lintool** [castorini/Anserini#5]
We probably also want to implement some type of phrasal query model... SDM seems like a good start.

**Comment by dyshi** [comment]
https://github.com/dyshi/Anserini/tree/feature-implement-sdm

I have a simple implementation tested on the Gov2 collection maybe we can merge this into the feature extractor branch after?

**Comment by Peilin-Yang** [comment]
It turns out that we can combine different query semantics from Lucene to construct SDM query.
For example, for ordered window and unordered window query, we can use [SpanQuery](https://lucene.apache.org/core/6_3_0/core/org/apache/lucene/search/spans/SpanQuery.html).
We then use `BooleanQuery` together with `BoostQuery` to construct the complete query.

**Comment by Peilin-Yang** [comment]
Merged as #359
