### ISSUE TITLE
Try out different analyzers on Tweets collection

### ISSUE THREAD

**Issue by lintool** [castorini/Anserini#50]
@xeniaqian94 It would be great for you to get some experience running end-to-end ad hoc experiments, which is a core activity of IR research. Let's start with something simple, like playing with different analyzers - currently, the tweet indexing uses PorterStemFilter. Try removing it and see what the effect is. So:
- change the analyzer to remove stemming
- rebuild index
- run retrieval experiments - report effects on MAP, P@30 (compare with original index).

It would be nice to also know the effects of indexing only English tweets, using same procedure above.

**Comment by xeniaqian94** [comment]
|                                                                         | MAP    | P@30   |
|-------------------------------------------------------------------------|--------|--------|
| Ad-hoc experiments                                                      | 0.3631 | 0.4109 |
| Remove stemming                                                         | 0.2237 | 0.2633 |
| With stemming, index only english users’ tweet                          | 0.3614 | 0.4054 |
| With stemming, index with EnglishAnalyzer                               | 0.3611 | 0.3878 |
| With stemming, use EnglishAnalyzer and index only english users’ tweet  | 0.3518 | 0.3898 |

Some draft conclusion,

1. Porter Stemming Algorithm is significantly useful for tweets index.

2. Even though expecting a increase in MAP, P@30 in English-only indexing, there is still a potential explanation to the actual slight MAP, P@30 decrease in English-only indexing(row 3, 4, 5):
It may be difficult to justify whether a tweet is indeed non-English since the language field is associated with user profile, e.g. a “fr” user may actually writes some tweets in “en”, therefore after filtering, some relevant actual english tweets by non-english users are filtered out and some non-relevant tweets are pushed into top 30 list. 

3. There’s a small defect found in Line 197, <code>io.anserini.document.twitter.Status.java</code>,
original: <code>status.lang = obj.get("lang").getAsString();  </code>
modified: <code>status.lang = obj.getAsJsonObject("user").get("lang").getAsString(); </code>
Here “lang” field is within “user” sub-Json object? </code>

**Comment by lintool** [comment]
@xeniaqian94 Please rerun the experiments above per our discussion and see if the numbers change...

**Comment by xeniaqian94** [comment]
__1. Effect of PorterStemFilter__

| Measure               | Mean                                | Standard Error | Test     | P-value |
|-----------------------|-------------------------------------|----------------|----------|---------|
| MAP_ad_hoc            | __0.363110__                            | 0.031869       |          |         |
| MAP_no_stemming       | __0.332631__                            | 0.032804       |          |         |
| ΔMAP | 0.030480 (0.004318, 0.056641) |                | paired t | __0.0234__  |

0.0234 < 0.05, reject the null hypothesis that, the difference between using or not using PorterStemmingFilter is not statistically significant. 


| Measure               | Mean                                | Standard Error | Test     | P-value |
|-----------------------|-------------------------------------|----------------|----------|---------|
| P@30_ad_hoc            | __0.410888__                            | 0.039596       |          |         |
| P@30_no_stemming       | __0.399998__                            | 0.040605       |          |         |
| ΔP@30 | 0.010890 (-0.021777, 0.043557) |                | paired t | __0.5059__  |

0.5059 > 0.05, do not reject the null hypothesis that, the difference between using or not using PorterStemmingFilter is not statistically significant.

This is the experiment branch with raw MAP and P@30 results per topics https://github.com/xeniaqian94/Anserini/tree/no_stemming

__2. Effect of indexing only English Tweets__

Should have finished this part in hours... But expecting locally to listen and store some 2015 tweets streams...  
(Will update results asap...)

Since in tweets2011 collection, json structure has only user's lang field, while 2015 json structure has a tweets' "lang" field. Testing on the tweets 2011 collection, can mostly only index english users' tweets.

![Settings Window](https://github.com/xeniaqian94/Useful-Markdown-Pic/raw/master/img/2011.png )![Settings Window](https://github.com/xeniaqian94/Useful-Markdown-Pic/raw/master/img/2015.png )

This difference made the previous results not justifiable, even in reverse trend.

|                                                                         | MAP    | P@30   |
|-------------------------------------------------------------------------|--------|--------|
| Ad-hoc experiments                                                      | 0.3631 | 0.4109 |
| With stemming, index only __english users’__ tweet                          | 0.3614 | 0.4054 |

**Comment by lintool** [comment]
We might revisit tweet tokenization at some later point in time, but closing issue for now.
