### ISSUE TITLE
Core17 qrels reference a bunch of docs not in Lucene index

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#515]
The Core17 qrels:

```
$ cut -f 3 -d ' ' src/main/resources/topics-and-qrels/qrels.core17.txt | sort | uniq > qrels.core17.docids
```

They reference a bunch of documents not in the Lucene index:

```
$ target/appassembler/bin/IndexUtils -index lucene-index.core17.pos+docvectors+rawdocs \
 -dumpDocVectors qrels.core17.docids -docVectorWeight TF_IDF
```

Need to look into this... may be a bug?

**Comment by emmileaf** [comment]
Most of these (304 documents) originate from photograph captions with no text within body tags, which is what contents of a NYT document are currently defined as. Because of this, they are treated as empty documents in the collection and are not indexed.

In these documents, the `articleAbstract` and `headline` fields contain potentially useful text. Would we want to define the contents of NYT documents to include them (or other fields) as well?

**Comment by lintool** [comment]
@emmileaf there's only one way to find out!

> In these documents, the articleAbstract and headline fields contain potentially useful text. Would we want to define the contents of NYT documents to include them (or other fields) as well?

Try this and run a retrieval experiment and see if AP or other metrics go up...
