### ISSUE TITLE
Simplify Ax feedback model

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#670]
The Ax feedback model currently depends on computing MI with respect to a working set: (N − 1) × R documents (assumed non-relevant) randomly sampled from the collection, excluding the first R documents.

See: https://cs.uwaterloo.ca/~jimmylin/publications/Yang_Lin_ECIR2019.pdf

Here's one idea to simplify the implementation - instead of sampling the working set, just use the entire collection as the working set. That is, compute MI wrt entire collection.

**Comment by lintool** [comment]
@emmileaf has a draft PR for this in #778 but @Peilin-Yang seems to questions the entire idea here: https://github.com/castorini/anserini/pull/778#pullrequestreview-274056631

So, we should first figure out whether this is worth doing... sorry @emmileaf we probably should have had this discussion with @Peilin-Yang first...

My motivation for this comes from the observation from our ECIR 2019 paper that there is quite a bit of variance associated with how we construct the reference set, see: https://cs.uwaterloo.ca/~jimmylin/publications/Yang_Lin_ECIR2019.pdf - Figure 6.

My interpretation - this is mostly an issue of smoothing. As we increase the size of the reference set, the variance should decrease... and in the limit, the reference set is the entire collection. This also lets us get rid of a parameter.

What do you think @Peilin-Yang is this an idea worth pursuing?

**Comment by Peilin-Yang** [comment]
I might be misunderstanding you ... 
What do you mean by `reference set`? Is that the `working set` in the paper?

1. If you are referring the working set, then the axiomatic algorithm won't work since you are essentially proposing to compute the MI between each query term and EVERY term in the collection. 
2. If you are referring the statistics (e.g. tf, idf) when computing MI, then that's what @emmileaf implemented (I think there is a bug) -- and we suffer from slowness.

Anyways, I slightly tend to object this proposal because: 
1. The original initiative of Anserini was to facilitate the reproducibility of IR. Thus I think we should only have reference implementations of the original papers/algorithms unless it is difficult to do so. Your proposal is actually a potential improvement of another algorithm and should be treated otherwise. 
2. The proposal (either case above) will introduce additional latency when reranking. The reason is listed above.
3. The variance in the Figure 6 of the paper seems only in Web collections. The algorithm performs pretty good and robust for Adhoc collections. And since this is also the case for many other algorithms, I think the problem lie in the Web collections or it is simply because we haven't found a systematic way to make it work.

But if you still would like to proceed, let @emmileaf fix the bug and see what would be the effectiveness impact?

**Comment by lukuang** [comment]
I do not think it is a good idea to make the whole collection the working set to compute mutual information. According to the [paper](https://www.eecis.udel.edu/~hfang/pubs/sigir06-expansion.pdf), there is a theoretic upper bound of the ratio r between the number of irrelevant documents to the number of relevant documents in the working set (i.e. TSSC2 in the paper).

**Comment by lintool** [comment]
Thus so agreed.
