### ISSUE TITLE
Publish pyserini in pypi

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#733]
@emmileaf how close are we to getting pyserini in a state where it's publishable on pypi, with transparent Java integration?

**Comment by emmileaf** [comment]
I think the main todo would be re-organizing into a standalone repo and adding configs/docs/etc. for pypi. Currently pyserini is set up to be a subdirectory within Anserini and was designed to be used within this folder structure. 

For publishing on pypi as a standalone package for `pip install`, perhaps we could upload `anserini-*-SNAPSHOT.fatjar.jar` from the latest anserini release somewhere within the package, instead of relying on building anserini from repo? Something like:

```
pyserini
| README.md
|
└───anserini-release
│   │   anserini-0.5.1-SNAPSHOT.fatjar.jar
|   |   …
└───search
│   │   pysearch.py
|   |   ...
|   …

```

Additional feature todos are multithreading support and maybe extending more of the wrapper interface (e.g. IndexUtils?), but the current version should be good to use for basic collection/search functionalities.

**Comment by lintool** [comment]
Let's revisit this after we cut v0.6.0 on the Java end!

**Comment by Impavidity** [comment]
You can do something like this to embed the jar file into python package.
```
from setuptools import find_packages, setup

setup(
  name='omniscient',
  version='0.0.1',
  author='Peng Shi, Michael Azmy',
  description='Knowledge Graph Toolkits',
  url='https://github.com/Impavidity/Omniscient',
  license='MIT',
  install_requires=['spacy', 'pyjnius'],
  package_data={"omniscient": [
    "resource/jars/tdbquery.jar",
    "resource/jars/anserini-0.3.1-SNAPSHOT-fatjar.jar",
    "resource/lexical/ordinal_lexical.tsv"
  ]},
  packages=find_packages(),
)
```
https://github.com/Impavidity/Omniscient/blob/master/setup.py

**Comment by emmileaf** [comment]
Awesome, thank you for this! :)

**Comment by lintool** [comment]
I'm going to start taking a look at this now that v0.6.0 has been published: https://packaging.python.org/tutorials/packaging-projects/

**Comment by lintool** [comment]
Check it out! https://pypi.org/project/pyserini/0.6.0.0/
New repo: https://github.com/castorini/pyserini

Thanks for all the code @emmileaf !

**Comment by lintool** [comment]
Closing issue here. All pyserini-specific issues should now be filed in that repo.
