### ISSUE TITLE
Add feature to search other fields in CORE corpus

### ISSUE THREAD

**Issue by bazingagin** [castorini/anserini#889]
We want to index `year` and `topics` in CORE corpus so that we can also search by these fields. Basically we need to modify `LuceneDocumentGenerator.java` or create a new `generator` that outputs more than `content` field for downstream searching.

**Comment by lintool** [comment]
Let's leave `LuceneDocumentGenerator` alone... probably best to create something like a `CoreDocumentGenerator` or something along those lines...

**Comment by ankit-shukla-dev** [comment]
Please add me, so that I can get the code

**Comment by ankit-shukla-dev** [comment]
I will clone and PR then

**Comment by lintool** [comment]
To be clear, this is the CORE dataset: https://core.ac.uk/services/dataset/

**Comment by edwinzhng** [comment]
Commenting so I can assign this issue to myself

**Comment by edwinzhng** [comment]
Hey @bazingagin it seems like the -storeTransformedDocs flag will set the "topics" and "year" fields as a stored document in Lucene, although there is a bug right now that causes "topics" to be an empty string instead of the actual value (this also affects all other JSON fields that are arrays). I can submit a change that for the array values, but did you want me to create the new generator regardless?

**Comment by lintool** [comment]
hey @edwinzhng to provide more context, our goal is to build rich search/browsing/exploration applications to the scientific literature, enabling, for example, analyses like these: https://medium.com/@nlpscholar/state-of-nlp-cbf768492f90

**Comment by lintool** [comment]
Closing with updated feature request in #979
